#############################################################################
# Makefile for building: DevCA
# Generated by qmake (2.01a) (Qt 4.8.7) on: Fri May 4 00:04:23 2018
# Project:  DevCA.pro
# Template: app
# Command: /usr/bin/qmake -spec /usr/share/qt4/mkspecs/linux-g++-64 -o Makefile DevCA.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/QtCore -I/usr/include/QtNetwork -I/usr/include/QtGui -I/usr/include -I. -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib64 -lQtGui -L/usr/lib64 -L/usr/X11R6/lib -lQtNetwork -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		qgridview.cpp \
		qgridtab.cpp \
		aboutdialog.cpp \
		qgridscene.cpp \
		qsidebutton.cpp \
		griddialog.cpp \
		settingsdialog.cpp \
		connectdialog.cpp \
		netdialog.cpp \
		sounddialog.cpp \
		caline.cpp \
		cagraphicsitemcreator.cpp \
		cablasttemplate.cpp \
		caconetemplate.cpp \
		camask.cpp \
		offsetdialog.cpp \
		network.cpp \
		ircnetwork.cpp moc_mainwindow.cpp \
		moc_qgridview.cpp \
		moc_qgridtab.cpp \
		moc_aboutdialog.cpp \
		moc_qgridscene.cpp \
		moc_griddialog.cpp \
		moc_settingsdialog.cpp \
		moc_connectdialog.cpp \
		moc_netdialog.cpp \
		moc_sounddialog.cpp \
		moc_cagraphicsitem.cpp \
		moc_cagraphicsitemcreator.cpp \
		moc_cablasttemplate.cpp \
		moc_caconetemplate.cpp \
		moc_camask.cpp \
		moc_offsetdialog.cpp \
		moc_network.cpp \
		moc_ircnetwork.cpp \
		qrc_DevCA.cpp
OBJECTS       = main.o \
		mainwindow.o \
		qgridview.o \
		qgridtab.o \
		aboutdialog.o \
		qgridscene.o \
		qsidebutton.o \
		griddialog.o \
		settingsdialog.o \
		connectdialog.o \
		netdialog.o \
		sounddialog.o \
		caline.o \
		cagraphicsitemcreator.o \
		cablasttemplate.o \
		caconetemplate.o \
		camask.o \
		offsetdialog.o \
		network.o \
		ircnetwork.o \
		moc_mainwindow.o \
		moc_qgridview.o \
		moc_qgridtab.o \
		moc_aboutdialog.o \
		moc_qgridscene.o \
		moc_griddialog.o \
		moc_settingsdialog.o \
		moc_connectdialog.o \
		moc_netdialog.o \
		moc_sounddialog.o \
		moc_cagraphicsitem.o \
		moc_cagraphicsitemcreator.o \
		moc_cablasttemplate.o \
		moc_caconetemplate.o \
		moc_camask.o \
		moc_offsetdialog.o \
		moc_network.o \
		moc_ircnetwork.o \
		qrc_DevCA.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		DevCA.pro
QMAKE_TARGET  = DevCA
DESTDIR       = 
TARGET        = DevCA

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): version.h ui_mainwindow.h ui_aboutdialog.h ui_griddialog.h ui_settingsdialog.h ui_connectdialog.h ui_netdialog.h ui_sounddialog.h ui_offsetdialog.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: DevCA.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib64/libQtGui.prl \
		/usr/lib64/libQtCore.prl \
		/usr/lib64/libQtNetwork.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++-64 -o Makefile DevCA.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/shared.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib64/libQtGui.prl:
/usr/lib64/libQtCore.prl:
/usr/lib64/libQtNetwork.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++-64 -o Makefile DevCA.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/DevCA1.0.0 || $(MKDIR) .tmp/DevCA1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/DevCA1.0.0/ && $(COPY_FILE) --parents mainwindow.h qgridview.h qgridtab.h aboutdialog.h qgridscene.h qsidebutton.h griddialog.h settingsdialog.h connectdialog.h version.h netdialog.h sounddialog.h caline.h cagraphicsitem.h cagraphicsitemcreator.h cablasttemplate.h caconetemplate.h camask.h offsetdialog.h network.h ircnetwork.h .tmp/DevCA1.0.0/ && $(COPY_FILE) --parents DevCA.qrc .tmp/DevCA1.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp qgridview.cpp qgridtab.cpp aboutdialog.cpp qgridscene.cpp qsidebutton.cpp griddialog.cpp settingsdialog.cpp connectdialog.cpp netdialog.cpp sounddialog.cpp caline.cpp cagraphicsitemcreator.cpp cablasttemplate.cpp caconetemplate.cpp camask.cpp offsetdialog.cpp network.cpp ircnetwork.cpp .tmp/DevCA1.0.0/ && $(COPY_FILE) --parents mainwindow.ui aboutdialog.ui griddialog.ui settingsdialog.ui connectdialog.ui netdialog.ui sounddialog.ui offsetdialog.ui .tmp/DevCA1.0.0/ && (cd `dirname .tmp/DevCA1.0.0` && $(TAR) DevCA1.0.0.tar DevCA1.0.0 && $(COMPRESS) DevCA1.0.0.tar) && $(MOVE) `dirname .tmp/DevCA1.0.0`/DevCA1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/DevCA1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


version.h: FORCE

check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp moc_qgridview.cpp moc_qgridtab.cpp moc_aboutdialog.cpp moc_qgridscene.cpp moc_griddialog.cpp moc_settingsdialog.cpp moc_connectdialog.cpp moc_netdialog.cpp moc_sounddialog.cpp moc_cagraphicsitem.cpp moc_cagraphicsitemcreator.cpp moc_cablasttemplate.cpp moc_caconetemplate.cpp moc_camask.cpp moc_offsetdialog.cpp moc_network.cpp moc_ircnetwork.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_qgridview.cpp moc_qgridtab.cpp moc_aboutdialog.cpp moc_qgridscene.cpp moc_griddialog.cpp moc_settingsdialog.cpp moc_connectdialog.cpp moc_netdialog.cpp moc_sounddialog.cpp moc_cagraphicsitem.cpp moc_cagraphicsitemcreator.cpp moc_cablasttemplate.cpp moc_caconetemplate.cpp moc_camask.cpp moc_offsetdialog.cpp moc_network.cpp moc_ircnetwork.cpp
moc_mainwindow.cpp: qgridview.h \
		qgridscene.h \
		caline.h \
		cagraphicsitem.h \
		qgridtab.h \
		cagraphicsitemcreator.h \
		griddialog.h \
		settingsdialog.h \
		netdialog.h \
		network.h \
		ircnetwork.h \
		connectdialog.h \
		mainwindow.h
	/usr/bin/moc $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_qgridview.cpp: qgridscene.h \
		caline.h \
		cagraphicsitem.h \
		qgridtab.h \
		qgridview.h \
		cagraphicsitemcreator.h \
		qgridview.h
	/usr/bin/moc $(DEFINES) $(INCPATH) qgridview.h -o moc_qgridview.cpp

moc_qgridtab.cpp: qgridview.h \
		qgridscene.h \
		caline.h \
		cagraphicsitem.h \
		qgridtab.h \
		cagraphicsitemcreator.h \
		qgridtab.h
	/usr/bin/moc $(DEFINES) $(INCPATH) qgridtab.h -o moc_qgridtab.cpp

moc_aboutdialog.cpp: aboutdialog.h
	/usr/bin/moc $(DEFINES) $(INCPATH) aboutdialog.h -o moc_aboutdialog.cpp

moc_qgridscene.cpp: caline.h \
		cagraphicsitem.h \
		qgridscene.h
	/usr/bin/moc $(DEFINES) $(INCPATH) qgridscene.h -o moc_qgridscene.cpp

moc_griddialog.cpp: qgridview.h \
		qgridscene.h \
		caline.h \
		cagraphicsitem.h \
		qgridtab.h \
		cagraphicsitemcreator.h \
		griddialog.h
	/usr/bin/moc $(DEFINES) $(INCPATH) griddialog.h -o moc_griddialog.cpp

moc_settingsdialog.cpp: settingsdialog.h
	/usr/bin/moc $(DEFINES) $(INCPATH) settingsdialog.h -o moc_settingsdialog.cpp

moc_connectdialog.cpp: connectdialog.h
	/usr/bin/moc $(DEFINES) $(INCPATH) connectdialog.h -o moc_connectdialog.cpp

moc_netdialog.cpp: network.h \
		ircnetwork.h \
		qgridtab.h \
		qgridview.h \
		qgridscene.h \
		caline.h \
		cagraphicsitem.h \
		cagraphicsitemcreator.h \
		connectdialog.h \
		netdialog.h
	/usr/bin/moc $(DEFINES) $(INCPATH) netdialog.h -o moc_netdialog.cpp

moc_sounddialog.cpp: sounddialog.h
	/usr/bin/moc $(DEFINES) $(INCPATH) sounddialog.h -o moc_sounddialog.cpp

moc_cagraphicsitem.cpp: cagraphicsitem.h
	/usr/bin/moc $(DEFINES) $(INCPATH) cagraphicsitem.h -o moc_cagraphicsitem.cpp

moc_cagraphicsitemcreator.cpp: cagraphicsitem.h \
		cagraphicsitemcreator.h
	/usr/bin/moc $(DEFINES) $(INCPATH) cagraphicsitemcreator.h -o moc_cagraphicsitemcreator.cpp

moc_cablasttemplate.cpp: cagraphicsitem.h \
		cablasttemplate.h
	/usr/bin/moc $(DEFINES) $(INCPATH) cablasttemplate.h -o moc_cablasttemplate.cpp

moc_caconetemplate.cpp: cagraphicsitem.h \
		caconetemplate.h
	/usr/bin/moc $(DEFINES) $(INCPATH) caconetemplate.h -o moc_caconetemplate.cpp

moc_camask.cpp: cagraphicsitem.h \
		camask.h
	/usr/bin/moc $(DEFINES) $(INCPATH) camask.h -o moc_camask.cpp

moc_offsetdialog.cpp: qgridview.h \
		qgridscene.h \
		caline.h \
		cagraphicsitem.h \
		qgridtab.h \
		cagraphicsitemcreator.h \
		offsetdialog.h
	/usr/bin/moc $(DEFINES) $(INCPATH) offsetdialog.h -o moc_offsetdialog.cpp

moc_network.cpp: ircnetwork.h \
		qgridtab.h \
		qgridview.h \
		qgridscene.h \
		caline.h \
		cagraphicsitem.h \
		cagraphicsitemcreator.h \
		connectdialog.h \
		network.h
	/usr/bin/moc $(DEFINES) $(INCPATH) network.h -o moc_network.cpp

moc_ircnetwork.cpp: ircnetwork.h
	/usr/bin/moc $(DEFINES) $(INCPATH) ircnetwork.h -o moc_ircnetwork.cpp

compiler_rcc_make_all: qrc_DevCA.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_DevCA.cpp
qrc_DevCA.cpp: DevCA.qrc \
		icoopen.xpm \
		icoremtab.xpm \
		sendbutton.png \
		orange16x16.bmp \
		dgrey16x16.bmp \
		resync.png \
		cyan16x16.bmp \
		brown16x16.bmp \
		circle12x12.png \
		circle18x18.png \
		icosound.xpm \
		coneTemplate16x16.png \
		green16x16.bmp \
		icodisconnect.xpm \
		stopbutton.png \
		icoaddtab.xpm \
		blue16x16.bmp \
		blastTemplate16x16.png \
		icoopensb.xpm \
		magenta16x16.bmp \
		ca.ico \
		grey16x16.bmp \
		circle14x14.png \
		playbutton.png \
		icomp3.xpm \
		triangle16x16.png \
		circle17x17.png \
		icosave.xpm \
		icobackgroundoffset.xpm \
		dcyan16x16.bmp \
		dyellow16x16.bmp \
		icogrid.xpm \
		blackout16x16.png \
		white16x16.bmp \
		black16x16.bmp \
		red16x16.bmp \
		icoclear.xpm \
		circle8x8.png \
		icoconnect.xpm \
		cross16x16.png \
		icobackground.xpm \
		icoclosecp.xpm \
		dred16x16.bmp \
		icoclosesb.xpm \
		dgreen16x16.bmp \
		dmagenta16x16.bmp \
		yellow16x16.bmp \
		icoaot.xpm \
		circle16x16.png \
		ca.xpm \
		icoopencp.xpm \
		dblue16x16.bmp \
		resize.png
	/usr/bin/rcc -name DevCA DevCA.qrc -o qrc_DevCA.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_aboutdialog.h ui_griddialog.h ui_settingsdialog.h ui_connectdialog.h ui_netdialog.h ui_sounddialog.h ui_offsetdialog.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_aboutdialog.h ui_griddialog.h ui_settingsdialog.h ui_connectdialog.h ui_netdialog.h ui_sounddialog.h ui_offsetdialog.h
ui_mainwindow.h: mainwindow.ui \
		qgridtab.h \
		qgridview.h \
		qsidebutton.h \
		qsidebutton.h \
		qgridview.h \
		qgridscene.h \
		caline.h \
		cagraphicsitem.h \
		qgridtab.h \
		cagraphicsitemcreator.h \
		qgridscene.h \
		caline.h \
		cagraphicsitem.h \
		qgridtab.h \
		qgridview.h \
		cagraphicsitemcreator.h
	/usr/bin/uic mainwindow.ui -o ui_mainwindow.h

ui_aboutdialog.h: aboutdialog.ui
	/usr/bin/uic aboutdialog.ui -o ui_aboutdialog.h

ui_griddialog.h: griddialog.ui
	/usr/bin/uic griddialog.ui -o ui_griddialog.h

ui_settingsdialog.h: settingsdialog.ui
	/usr/bin/uic settingsdialog.ui -o ui_settingsdialog.h

ui_connectdialog.h: connectdialog.ui
	/usr/bin/uic connectdialog.ui -o ui_connectdialog.h

ui_netdialog.h: netdialog.ui
	/usr/bin/uic netdialog.ui -o ui_netdialog.h

ui_sounddialog.h: sounddialog.ui
	/usr/bin/uic sounddialog.ui -o ui_sounddialog.h

ui_offsetdialog.h: offsetdialog.ui
	/usr/bin/uic offsetdialog.ui -o ui_offsetdialog.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		qgridview.h \
		qgridscene.h \
		caline.h \
		cagraphicsitem.h \
		qgridtab.h \
		cagraphicsitemcreator.h \
		griddialog.h \
		settingsdialog.h \
		netdialog.h \
		network.h \
		ircnetwork.h \
		connectdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		qgridview.h \
		qgridscene.h \
		caline.h \
		cagraphicsitem.h \
		qgridtab.h \
		cagraphicsitemcreator.h \
		griddialog.h \
		settingsdialog.h \
		netdialog.h \
		network.h \
		ircnetwork.h \
		connectdialog.h \
		aboutdialog.h \
		sounddialog.h \
		offsetdialog.h \
		ui_mainwindow.h \
		qsidebutton.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

qgridview.o: qgridview.cpp qgridview.h \
		qgridscene.h \
		caline.h \
		cagraphicsitem.h \
		qgridtab.h \
		cagraphicsitemcreator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qgridview.o qgridview.cpp

qgridtab.o: qgridtab.cpp qgridtab.h \
		qgridview.h \
		qgridscene.h \
		caline.h \
		cagraphicsitem.h \
		cagraphicsitemcreator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qgridtab.o qgridtab.cpp

aboutdialog.o: aboutdialog.cpp aboutdialog.h \
		ui_aboutdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o aboutdialog.o aboutdialog.cpp

qgridscene.o: qgridscene.cpp qgridscene.h \
		caline.h \
		cagraphicsitem.h \
		cablasttemplate.h \
		camask.h \
		caconetemplate.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qgridscene.o qgridscene.cpp

qsidebutton.o: qsidebutton.cpp qsidebutton.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qsidebutton.o qsidebutton.cpp

griddialog.o: griddialog.cpp griddialog.h \
		qgridview.h \
		qgridscene.h \
		caline.h \
		cagraphicsitem.h \
		qgridtab.h \
		cagraphicsitemcreator.h \
		ui_griddialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o griddialog.o griddialog.cpp

settingsdialog.o: settingsdialog.cpp settingsdialog.h \
		ui_settingsdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o settingsdialog.o settingsdialog.cpp

connectdialog.o: connectdialog.cpp connectdialog.h \
		ui_connectdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o connectdialog.o connectdialog.cpp

netdialog.o: netdialog.cpp netdialog.h \
		network.h \
		ircnetwork.h \
		qgridtab.h \
		qgridview.h \
		qgridscene.h \
		caline.h \
		cagraphicsitem.h \
		cagraphicsitemcreator.h \
		connectdialog.h \
		ui_netdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o netdialog.o netdialog.cpp

sounddialog.o: sounddialog.cpp sounddialog.h \
		ui_sounddialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sounddialog.o sounddialog.cpp

caline.o: caline.cpp caline.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o caline.o caline.cpp

cagraphicsitemcreator.o: cagraphicsitemcreator.cpp cagraphicsitemcreator.h \
		cagraphicsitem.h \
		cablasttemplate.h \
		caconetemplate.h \
		camask.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cagraphicsitemcreator.o cagraphicsitemcreator.cpp

cablasttemplate.o: cablasttemplate.cpp cablasttemplate.h \
		cagraphicsitem.h \
		qgridscene.h \
		caline.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cablasttemplate.o cablasttemplate.cpp

caconetemplate.o: caconetemplate.cpp caconetemplate.h \
		cagraphicsitem.h \
		qgridscene.h \
		caline.h \
		cablasttemplate.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o caconetemplate.o caconetemplate.cpp

camask.o: camask.cpp camask.h \
		cagraphicsitem.h \
		qgridscene.h \
		caline.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o camask.o camask.cpp

offsetdialog.o: offsetdialog.cpp offsetdialog.h \
		qgridview.h \
		qgridscene.h \
		caline.h \
		cagraphicsitem.h \
		qgridtab.h \
		cagraphicsitemcreator.h \
		ui_offsetdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o offsetdialog.o offsetdialog.cpp

network.o: network.cpp network.h \
		ircnetwork.h \
		qgridtab.h \
		qgridview.h \
		qgridscene.h \
		caline.h \
		cagraphicsitem.h \
		cagraphicsitemcreator.h \
		connectdialog.h \
		netdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o network.o network.cpp

ircnetwork.o: ircnetwork.cpp ircnetwork.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ircnetwork.o ircnetwork.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_qgridview.o: moc_qgridview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qgridview.o moc_qgridview.cpp

moc_qgridtab.o: moc_qgridtab.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qgridtab.o moc_qgridtab.cpp

moc_aboutdialog.o: moc_aboutdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_aboutdialog.o moc_aboutdialog.cpp

moc_qgridscene.o: moc_qgridscene.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qgridscene.o moc_qgridscene.cpp

moc_griddialog.o: moc_griddialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_griddialog.o moc_griddialog.cpp

moc_settingsdialog.o: moc_settingsdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_settingsdialog.o moc_settingsdialog.cpp

moc_connectdialog.o: moc_connectdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_connectdialog.o moc_connectdialog.cpp

moc_netdialog.o: moc_netdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_netdialog.o moc_netdialog.cpp

moc_sounddialog.o: moc_sounddialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_sounddialog.o moc_sounddialog.cpp

moc_cagraphicsitem.o: moc_cagraphicsitem.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_cagraphicsitem.o moc_cagraphicsitem.cpp

moc_cagraphicsitemcreator.o: moc_cagraphicsitemcreator.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_cagraphicsitemcreator.o moc_cagraphicsitemcreator.cpp

moc_cablasttemplate.o: moc_cablasttemplate.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_cablasttemplate.o moc_cablasttemplate.cpp

moc_caconetemplate.o: moc_caconetemplate.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_caconetemplate.o moc_caconetemplate.cpp

moc_camask.o: moc_camask.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_camask.o moc_camask.cpp

moc_offsetdialog.o: moc_offsetdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_offsetdialog.o moc_offsetdialog.cpp

moc_network.o: moc_network.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_network.o moc_network.cpp

moc_ircnetwork.o: moc_ircnetwork.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ircnetwork.o moc_ircnetwork.cpp

qrc_DevCA.o: qrc_DevCA.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_DevCA.o qrc_DevCA.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

